name: redis # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '6.2.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: In-memory database that persists on disk. http://redis.io # 79 char long summary
description: Redis is an in-memory data structure project implementing a distributed,
            in-memory key-value database with optional durability.

license: ISC
icon: snap/local/assets/snap-icon.png
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  redis-server:
    # modify redis.conf in /var/snap/<snap-name>/common/redis.conf
    command: bin/redis-server $SNAP_COMMON/redis.conf
    # daemon: simple
    plugs: [network, network-bind]
  redis-benchmark:
    command: bin/redis-benchmark
    plugs: [network]
  redis-check-aof:
    command: bin/redis-check-aof
  redis-check-rdb:
    command: bin/redis-check-rdb
  redis-cli:
    command: bin/redis-cli
    plugs: [network]
  redis-sentinel:
    command: bin/redis-sentinel
    plugs: [network, network-bind]

parts:
  redis:
    plugin: make
    source: https://github.com/redis/redis.git
    source-tag: '6.2.5'
    build-packages:
      - build-essential
    make-parameters:
      - "PREFIX=$SNAPCRAFT_PART_INSTALL"

  redis-customizations:
    plugin: dump
    source: redis/
    organize:
      config/*: config/redis/

